# 0: throughput, loosing messages, 1 compromise, -1 (all): reliability.
acks: -1
# true: enable idempotent producer
enable.idempotence: true
# use batching for better throughput
# tune the batch.size it is given in bytes
batch.size: 16384
# linger.ms: time to wait for more messages to batch
linger.ms: 0
# use compression for better throughput
# options: none, gzip, snappy, lz4, zstd
compression.type: none