WEBSHOP_SERVICE_PORT = 5001
PRODUCT_SERVICE_PORT = 5002
PRICE_SERVICE_PORT = 5003

PRODUCT_SERVICE_URL = f'http://localhost:{PRODUCT_SERVICE_PORT}'
PRICE_SERVICE_URL = f'http://localhost:{PRICE_SERVICE_PORT}'