{
 "title": "Kafka",
 "tags": [ "Kafka" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "kafka_broker",
    "label": "Broker",
    "query": "label_values(kafka_server_replicamanager_leadercount,job)"
   },
   {
    "name": "kafka_topic",
    "label": "Topic",
    "query": "query_result(kafka_cluster_partition_replicascount{})"
   },
   {
    "name": "kafka_partition",
    "label": "Partition",
    "query": "query_result(kafka_log_log_size{topic=~\"$kafka_topic\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Brokers Online",
   "type": "singlestat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount)"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "singlestat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount)"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "singlestat",
   "description": "Unclean leader election rate",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kafka_controller_controllerstats_uncleanleaderelections_total[5m]))"
    }
   ]
  },
  {
   "title": "Online Replicas",
   "type": "singlestat",
   "description": "Replicas that are online",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount)"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions)"
    }
   ]
  },
  {
   "title": "Partitions at mininimum ISR",
   "type": "singlestat",
   "description": "Number of partitions which are at their minimum in sync replica count (| ISR | == | min.insync.replicas |).",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_atminisr)"
    }
   ]
  },
  {
   "title": "Partitions under mininimum ISR",
   "type": "singlestat",
   "description": "Number of partitions which are under their minimum in sync replica count (| ISR | < | min.insync.replicas |).",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr)"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "singlestat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount)"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Incoming Byte Rate",
   "type": "singlestat",
   "description": "Total Incoming Byte Rate",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{topic=~\"$kafka_topic\",topic!=\"\",job=~\"$kafka_broker\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Outgoing Byte Rate",
   "type": "singlestat",
   "description": "Total Outgoing Byte Rate",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesout_total{topic=~\"$kafka_topic\",topic!=\"\",job=~\"$kafka_broker\"}[1m]))"
    }
   ]
  },
  {
   "title": "Incoming Messages Rate",
   "type": "singlestat",
   "description": "Incoming Messages Rate",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"$kafka_topic\",topic!=\"\",job=~\"$kafka_broker\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Produce Request Rate",
   "type": "singlestat",
   "description": "Total Produce Request Rate",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalproducerequests_total{topic=~\"$kafka_topic\",topic!=\"\",job=~\"$kafka_broker\"}[1m]))"
    }
   ]
  },
  {
   "title": "Byte Rate",
   "type": "graph",
   "description": "Byte Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{topic=~\"$kafka_topic\",topic!=\"\",job=~\"$kafka_broker\"}[1m]))",
     "legendFormat": "Total Incoming Byte Rate"
    },
    {
     "expr": "-sum(irate(kafka_server_brokertopicmetrics_bytesout_total{topic=~\"$kafka_topic\",topic!=\"\",job=~\"$kafka_broker\"}[1m]))",
     "legendFormat": "Total Outgoing Byte Rate"
    }
   ]
  },
  {
   "title": "Messages In Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"$kafka_topic\",topic!=\"\",job=~\"$kafka_broker\"}[1m]))",
     "legendFormat": "Total Incoming Messages Rate"
    }
   ]
  },
  {
   "title": "Produce Request Rate",
   "type": "graph",
   "description": "Produce Request Rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalproducerequests_total{topic=~\"$kafka_topic\",topic!=\"\",job=~\"$kafka_broker\"}[1m]))",
     "legendFormat": "Total Produce Request Rate"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedproducerequests_total{topic=~\"$kafka_topic\",topic!=\"\",job=~\"$kafka_broker\"}[1m]))",
     "legendFormat": "Failed Produce Request Rate"
    }
   ]
  },
  {
   "title": "Fetch Request Rate",
   "type": "graph",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{topic=~\"$kafka_topic\",topic!=\"\",job=~\"$kafka_broker\"}[1m]))",
     "legendFormat": "Fetch Request Rate"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedfetchrequests_total{topic=~\"$kafka_topic\",topic!=\"\",job=~\"$kafka_broker\"}[1m]))",
     "legendFormat": "Failed Fetch Request Rate"
    }
   ]
  },
  {
   "title": "Network Processor Avg Idle Percent",
   "type": "graph",
   "description": "Network Processor Avg Idle Percent",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "kafka_network_socketserver_networkprocessoravgidlepercent{job=~\"$kafka_broker\"}*100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Log Size",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_log_log_size{topic=~\"$kafka_topic\",partition=~\"$kafka_partition\",job=~\"$kafka_broker\"}",
     "legendFormat": "{{topic}}:{{partition}}"
    }
   ]
  }
 ]
}