#!/usr/bin/env bash
echo "Testing Kafka…"
echo -n "Kafka 1"
kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1 || echo -ne "\t !!! Not"
echo -e "\tOK"
echo -n "Kafka 2"
kafka-broker-api-versions.sh --bootstrap-server localhost:9093 > /dev/null 2>&1 || echo -ne "\t !!! Not"
echo -e "\tOK"
echo -n "Kafka 3"
kafka-broker-api-versions.sh --bootstrap-server localhost:9094 > /dev/null 2>&1 || echo -ne "\t !!! Not"
echo -e "\tOK"
echo "Happy Hacking!"