WEBSHOP_SERVICE_PORT = 5011
PRODUCT_SERVICE_PORT = 5012
PRICE_SERVICE_PORT = 5013

KAFKA_BOOTSTRAP_SERVERS = 'localhost:9092'
PRODUCT_TOPIC = 'products'
PRICE_TOPIC = 'prices'
INVENTORY_TOPIC = 'inventory'