services:
  kafka-ui:
    container_name: kafka-ui
    image: kafbat/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: localhost:9092,localhost:9093,localhost:9094
      AUTH_TYPE: "LOGIN_FORM"
      SPRING_SECURITY_USER_NAME: user
      SPRING_SECURITY_USER_PASSWORD: kafkaisfun
      SERVER_PORT: 7005
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://localhost:8090
      # TODO: Uncomment this for the schema management lab
      # KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://localhost:8081
    network_mode: host
    restart: always
